version: '3.4'

services:
  introduction-api:
    container_name: introduction-api
    image: mdevivoregistry.azurecr.io/intro
    build:
      context: ./introduction-api
      dockerfile: Dockerfile
    environment:
      - "MSSQL_PASSWORD=<>"
    ports:
      - "127.0.0.1:8080:80"
#  sqlserver:
#    container_name: mssqlserver
#    image: mcr.microsoft.com/mssql/server:2022-latest
#    ports:
#      - "127.0.0.1:1443:1443"
#    environment:
#      - "ACCEPT_EULA=Y"
#      - "MSSQL_SA_PASSWORD=StrongPassword2022"
