version: '3.4'

services:
  introduction-api:
    container_image: introduction-api
    image: ${DOCKER_REGISTRY-}introductionapi
    build:
      context: .
      dockerfile: introduction-api/Dockerfile
    environments:
      - "MSSQL_PASSWORD=<mssqlpassword>"
  sqlserver:
    container_name: mssqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "127.0.0.1:1443:1443"
    environments:
      - "ACCEPT_EULA=Y"
      - "MSSQL_SA_PASSWORD=StrongPassword2022"
